### PR TITLE
Accept only '1' or '0' in get_bool()

### PR DESCRIPTION
**Pull request by jreut**
I'm happy to hear a justification for only accepting the string `"1"` as a truthy value, but it's a bit surprising.

### CODE REVIEW

**Comment by mattbriancon** [comment]
`1` is the convention we've used for a long time (since way before `mbq.env`). I don't actually care what the value is but I can't think of a reason to have two "true" values and since it's already `1`, I'm inclined to leave it.

**Comment by thieman** [comment]
I think there are two solutions here on the optimal frontier:

1. Try to interpret what the user meant, and accept both `1` and any version of `true` as True
2. Force the user to pass `1` and if any value other than `0`, `1`, or unset is passed, throw an error.

The current implementation is problematic because it's silently failing, returning `False` instead of telling you you're using the lib wrong.

**Comment by mattbriancon** [comment]
+1 to the second option. I don't see any reason to allow for "creativity" and unless you're planning to update all the env vars for all the services to use `true` instead of `1` then we're stuck with `1`.

**Review by mattbriancon — APPROVED** [review]

**Pull request merged**
